- project:
    name: opendev/ci-sandbox
    check:
      jobs:
        - smoketest
        - base-intel-no-devstack

- project-template:
    name: openstack-taas-jobs
    description: |
      Runs Sriov job on tap-as-a-service project
    check:
      jobs:
        - tap-as-a-service-dsvm-intel-sriov:
            branches: master
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^doc/.*$
              - ^neutron/locale/.*$
              - ^neutron/tests/unit/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tools/.*$
              - ^tox.ini$

- project-template:
    name: openstack-lower-constraints-jobs
    description: |
      Runs openstack-tox-lower-constraints in the check pipeline.
    check:
      jobs:
        - openstack-tox-lower-constraints:
            branches: master

- project-template:
    name: tap-as-a-service-tempest-plugin-jobs
    check:
      jobs:
        - tap-as-a-service-tempest-plugin:
            branches: master

- project-template:
    name: system-required
    description: |
      Jobs that *every* project in OpenStack CI should have by default.

      This is automatically added to all projects in OpenStack CI, no
      repository should use this directly.
    # Include a check queue so that initially every repo has a check queue
    # and we can report invalid zuul.yaml files.
    check:
      jobs: []

- job:
    name: tap-as-a-service-dsvm-intel-sriov
    parent: base
    description: |
      setup devstack and test port mirroring
      on intel nic using tempest.
    required-projects:
      - opendev.org/x/tap-as-a-service
      - opendev.org/openstack/devstack
      - opendev.org/opendev/ci-sandbox
      - opendev.org/openstack/neutron
    pre-run: playbooks/inteltaptest/pre.yaml
    run: playbooks/inteltaptest/run.yaml
    nodeset:
      nodes:
        - name: controller
          label: ubuntu-xenial-metal
    vars:
      test_command: "touch sriov_file"
      dest_dir: "/opt/stack"
      devstack_dir: "{{ dest_dir }}/devstack"
      output_dir: "{{ zuul_output_dir }}/logs"
      sys_info_dir: "{{ output_dir }}/sys_info"
      pip_info_log: "{{ sys_info_dir }}/pip_log.txt"

- job:
    name: tap-as-a-service-tempest-plugin
    parent: devstack-tempest
    description: |
      Perform setup common to all tap-as-a-service tempest tests


- job:
    name: base-intel-devstack
    parent: devstack-minimal
    description: |
      Minimal job including devstack pre/post
      Inherit from this job if you need base pre and post
      roles and devstack pre and post roles.
      TODO- ref for above roles
    nodeset:
      # override this node set if needed
      nodes:
        - name: controller
          label: ubuntu-bionic
    required-projects:
      # amend this to include project src as needed
      - opendev.org/openstack/devstack
    roles:
      # amend this to include project roles as needed
      - zuul: zuul/zuul-jobs
      - zuul: openstack/devstack
    pre-run: playbooks/base-intel/pre.yaml
    run: playbooks/base-intel-devstack/run.yaml
    post-run: playbooks/base-intel/post.yaml
    vars:
      ansible_user_dir: /srv/static/ansible_user_logs/
      dest_dir: "/opt/stack"
      devstack_dir: "{{ dest_dir }}/devstack"
      devstack_repo: git://github.com/openstack-dev/devstack.git
      devstack_version: "master"
      # TODO: detect host IP from zuul vars
      host_ip: "{{ ansible_default_ipv4.address }}"
      no_log: false
      os_password: devstack
      outfile: "{{ output_dir }}/{{ testfile }}"
      output_dir: "{{ zuul_output_dir }}/logs"
      pip_info_log: "{{ sys_info_dir }}/pip_log.txt"
      sys_info_dir: "{{ output_dir }}/sys_info"
      userlogfile: "{{ ansible_user_dir }}/user_output_log.txt"
      zuul_log_verbose: true
      zuul_output_dir: /srv/static/logs
      devstack_services:
        # Ignore any default set by devstack. Emit a "disable_all_services".
        base: false
        # Keystone services
        key: true
      devstack_localrc:
        DEST: "{{ dest_dir }}"
        DATA_DIR: "{{ dest_dir }}/data"
        GIT_BASE: "https://git.openstack.org"
        # Logging
        LOGFILE: "{{ output_dir }}/stack.sh.log"
        SCREEN_LOGDIR: "{{ output_dir }}/screen"
        VERBOSE: true
        ENABLE_DEBUG_LOG_LEVEL: true
        ENABLE_VERBOSE_LOG_LEVEL: true
        # the following is the boilerplate from upstream
        USE_PYTHON3: true
        INSTALL_TESTONLY_PACKAGES: true
        # ip addresses
        HOST_IP: "{{ host_ip }}"
        SERVICE_HOST: "{{ host_ip }}"
        VNCSERVER_LISTEN: 0.0.0.0
        VNCSERVER_PROXYCLIENT_ADDRESS: "{{ host_ip }}"
        # passwords
        OS_USERNAME: demo
        OS_PASSWORD: "{{ os_password }}"
        ADMIN_PASSWORD: "{{ os_password }}"
        MYSQL_PASSWORD: "{{ os_password }}"
        DATABASE_PASSWORD: "{{ os_password }}"
        RABBIT_PASSWORD: "{{ os_password }}"
        SERVICE_PASSWORD: "{{ os_password }}"
        SERVICE_TOKEN: "{{ os_password }}"
        # misc
        DEBUG_LIBVIRT_COREDUMPS: true
        NOVA_VNC_ENABLED: true
      tox_envlist: dsvm-functional
      tox_install_siblings: false
      zuul_copy_output:
        # We need to copy directory with logs to have it in job artifacts also,
        # /opt/stack/logs is default logs directory defined in neutron's
        # tox.ini file
        '{{ output_dir }}/dsvm-functional-logs': logs

- job:
    name: base-intel-no-devstack
    parent: base-intel-devstack
    description: |
      minimal job including devstack pre/post
      Inherit from this job if you just need base
      pre and post playbooks.
      Variables including paths and passwords should
      be mirrored with base-intel-devstack
    run: playbooks/base-intel-no-devstack/run.yaml
    vars:
      testfile: testfile1.txt

- job:
    name: test-baremetal
    parent: base-intel-no-devstack
    description: |
      minimal job including devstack pre/post
    run: playbooks/base-intel-no-devstack/run.yaml
    required-projects:
      - opendev.org/x/tap-as-a-service
      - opendev.org/openstack/devstack
      - opendev.org/opendev/ci-sandbox
      - opendev.org/openstack/neutron
    vars:
      testfile: testfile1.txt
    nodeset:
      nodes:
        - name: controller
          label: ubuntu-xenial-metal

- job:
    name: smoketest
    description: |
      minimal test to verify infra is working
    pre-run: playbooks/base-intel/pre.yaml
    run: playbooks/base-intel-no-devstack/run.yaml
    post-run: playbooks/base-intel/post.yaml

