- hosts: all
  roles:
    - prepare-host-virtual-interfaces
    - run-devstack
    - test-tap-as-a-service

# We run tests only on one node, regardless how many nodes are in the system
- hosts: tempest
  roles:
    # from tempest
    - setup-tempest-run-dir
    - setup-tempest-data-dir
    - acl-devstack-files
    - run-tempest
    # run taas test after tempest is setup properly
    - test-tap-as-a-service
